/** Readable names for audit-log actions and roles — same wording as the website's Audit Log. */
export const ACTION_LABELS: Record<string, string> = {
  SIGNED_IN: 'Signed in',
  SIGN_IN_FAILED: 'Failed sign-in',
  SIGN_IN_LOCKED_OUT: 'Sign-in locked out',
  PASSWORD_CHANGED: 'Changed password',
  PASSWORD_RESET_REQUESTED: 'Asked for a password reset link',
  PASSWORD_RESET: 'Reset password with an email link',
  ACCOUNT_SET_UP: 'Set up account from invite',
  ACCOUNT_LINK_SENT: 'Emailed an invite or reset link',
  MFA_ENABLED: 'Turned on two-step verification',
  MFA_DISABLED: 'Turned off two-step verification',
  MFA_CODE_FAILED: 'Wrong two-step code',
  MFA_RECOVERY_CODES_REPLACED: 'Replaced recovery codes',
  MFA_RESET: 'Reset two-step verification',
  SCHOOL_ADDED_TO_DISTRICT: 'School added to district',
  DISTRICT_ADMIN_ADDED: 'District admin added',
  DISTRICT_ADMIN_REMOVED: 'District admin removed',
  SCHOOL_REGISTERED: 'Registered school',
  DROPOFF_REQUESTED: 'Requested drop-off',
  PICKUP_REQUESTED: 'Requested pickup',
  DROPOFF_ACCEPTED: 'Accepted drop-off',
  PICKUP_ACCEPTED: 'Accepted pickup',
  DROPOFF_DECLINED: 'Declined drop-off',
  PICKUP_DECLINED: 'Declined pickup',
  PICKUP_CODE_REJECTED: 'Wrong pickup code entered',
  PICKUP_CODE_LOCKED_OUT: 'Pickup cancelled (too many wrong codes)',
  PICKUP_PIN_CREATED: 'Created pickup PIN',
  PICKUP_PIN_CHANGED: 'Changed pickup PIN',
  PICKUP_PIN_RESET_REQUESTED: 'Asked for a pickup PIN reset email',
  PICKUP_PIN_RESET: 'Reset pickup PIN by email',
  PICKUP_PIN_FAILED: 'Wrong pickup PIN entered',
  PICKUP_PIN_LOCKED_OUT: 'Pickup requests locked (too many wrong PINs)',
  CLASS_ROSTER_VIEWED: 'Viewed class roster',
  ATTENDANCE_HISTORY_VIEWED: 'Viewed attendance history',
  ATTENDANCE_VIEWED: 'Viewed attendance',
  ATTENDANCE_MARKED: 'Marked attendance',
  STUDENT_LIST_VIEWED: 'Viewed student list',
  PARENT_LIST_VIEWED: 'Viewed parent list',
  STUDENT_CREATED: 'Added student',
  STUDENT_STATUS_CHANGED: 'Changed student status',
  STUDENT_REMOVED: 'Removed student',
  STUDENT_RESTORED: 'Restored student',
  STUDENT_RECORD_EXPORTED: "Exported a student's record",
  STUDENT_PERMANENTLY_DELETED: 'Permanently deleted student',
  SCHOOL_DATA_EXPORTED: 'Exported school data',
  RETENTION_SETTINGS_CHANGED: 'Changed retention settings',
  PICKUP_HISTORY_PURGED: 'Deleted old drop-off/pickup records',
  PICKUP_AUTHORIZATION_CHANGED: 'Changed pickup authorization',
  PICKUP_AUTHORIZATION_REQUESTED: 'Asked to authorize an adult',
  PICKUP_AUTHORIZATION_APPROVED: 'Approved an adult',
  PICKUP_AUTHORIZATION_REJECTED: 'Rejected an adult',
  PARENT_CREATED: 'Added parent',
  PARENT_STATUS_CHANGED: 'Changed parent status',
  PARENT_REMOVED: 'Removed parent',
  STAFF_CREATED: 'Added staff member',
  STAFF_UPDATED: 'Edited staff member',
  STAFF_STATUS_CHANGED: 'Changed staff status',
  STAFF_REMOVED: 'Removed staff member',
  SCHOOL_SETTINGS_UPDATED: 'Changed school settings',
  LOCATION_CREATED: 'Added location',
  LOCATION_UPDATED: 'Changed location',
  LOCATION_STATUS_CHANGED: 'Suspended or reactivated location',
  LOCATION_REMOVED: 'Deleted location',
  CLASS_CREATED: 'Added class',
  PROMOTION_RUN: 'Ran grade promotion',
  SCHOOL_YEAR_ACTIVATED: 'Activated school year',
  SUPPORT_SESSION_STARTED: 'Started a support session',
  SUPPORT_SESSION_ENDED: 'Ended a support session',
  SUPPORT_VIEWED: 'Viewed a page in a support session',
  SUPPORT_CHANGE: 'Made a change in a support session',
  SCHOOL_CREATED: 'Created school',
  SCHOOL_UPDATED: 'Edited school',
  SCHOOL_SUSPENDED: 'Suspended school',
  SCHOOL_REACTIVATED: 'Reactivated school',
  SCHOOL_ARCHIVED: 'Archived school',
  ADMINISTRATOR_CREATED: 'Created school administrator',
  PLATFORM_SCHOOL_VIEWED: 'Viewed school (platform)',
  PLATFORM_USERS_VIEWED: 'Viewed school people (platform)',
  PLATFORM_STUDENTS_VIEWED: 'Viewed school students (platform)',
  PLATFORM_OPERATIONS_VIEWED: 'Viewed drop-off/pickup activity (platform)',
  INCIDENT_REVIEWED: 'Reviewed a declined request',
  SESSION_ENDED_BY_PLATFORM: 'Ended an admin session',
  LEGAL_HOLD_SET: 'Placed school on legal hold',
  LEGAL_HOLD_RELEASED: 'Released legal hold',
  DATA_EXPORT_REQUESTED: 'Logged an export request',
  DATA_DELETION_REQUESTED: 'Logged a deletion request',
  DATA_REQUEST_UNDER_REVIEW: 'Started reviewing a data request',
  DATA_REQUEST_APPROVED: 'Approved a data request',
  DATA_REQUEST_REJECTED: 'Rejected a data request',
  DATA_REQUEST_PROCESSING: 'Started carrying out a data request',
  DATA_REQUEST_COMPLETED: 'Completed a data request',
  DATA_EXPORTED: 'Downloaded a data export',
  EMAIL_RETRIED: 'Retried an email',
  ANNOUNCEMENT_SENT: 'Sent a platform announcement',
  REPORT_EXPORT_REQUESTED: 'Started a report export',
  REPORT_EXPORTED: 'Downloaded a report',
  BILLING_PLAN_CREATED: 'Created a billing plan',
  BILLING_PLAN_UPDATED: 'Changed a billing plan',
  SUBSCRIPTION_CHANGED: "Changed a school's subscription",
  INVOICE_CREATED: 'Created an invoice',
  INVOICE_ISSUED: 'Issued an invoice',
  INVOICE_VOIDED: 'Voided an invoice',
  PAYMENT_RECORDED: 'Recorded a payment',
  EMAIL_CONNECTION_CHECKED: 'Tested the email connection',
  PLATFORM_ADMIN_ADDED: 'Added platform administrator',
  PLATFORM_ADMIN_DISABLED: 'Disabled platform administrator',
  PLATFORM_ADMIN_REACTIVATED: 'Reactivated platform administrator',
  ROLE_CHANGED: 'Changed platform role',
};
export const ROLE_LABELS: Record<string, string> = {
  school_admin: 'Admin', staff: 'Front Desk', teacher: 'Teacher', parent: 'Parent', admin: 'Admin', platform_super_admin: 'Platform Admin', system: 'Automatic',
  district_admin: 'District Admin', platform_operator: 'Platform Operator',
  SUPER_ADMIN: 'Super Admin', PLATFORM_ADMIN: 'Platform Admin', SUPPORT_ADMIN: 'Support Admin', BILLING_ADMIN: 'Billing Admin',
};
export const actionLabel = (action: string) => ACTION_LABELS[action] ?? action;
